version: '3'
services:
  myapp:
    container_name: api-recipes
    restart: always
    build: .
    ports:
      - '8081:8081'
      - '8082:8082'
    environment:
      - PORT=8081
      - REDIS_HOST=api-recipes-redis
      - REDIS_EXPIRATION=86400
      - GIPHY_API_KEY=
      - GIPHY_REDIS_KEY=giphy_repository
      - RECIPE_PUPPY_REDIS_KEY=recipe_puppy_repository
  redis:
    container_name: api-recipes-redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'